name: 'Container Build'

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  IMAGE_NAME: ci-cd-demo

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    
    steps:   
      - uses: actions/checkout@v3
      - name: docker-build
        run: docker build . --file Dockerfile --tag $IMAGE_NAME:${GITHUB_SHA}
